name: Defang
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: Whether to deploy up or down
        required: true
        default: up
        type: choice
        options:
          - up
          - down
      stack:
        description: The stack to deploy up or down. (Leave blank for default)
        default: production
jobs:
  defang:
    name: Defang ${{ github.event.inputs.action || 'up' }} ${{ github.event.inputs.stack || 'production' }}
    runs-on: ubuntu-latest
    timeout-minutes: 70
    permissions:
      contents: read
      id-token: write
    concurrency:
      cancel-in-progress: false
      group: deploy-hackathon26-${{ github.event.inputs.stack || 'production' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Defang ${{ github.event.inputs.action || 'up' }} ${{ github.event.inputs.stack || 'production' }}
        uses: DefangLabs/defang-github-action@v2
        env:
          CONSENTKEYS_CLIENT_SECRET: ${{ secrets.CONSENTKEYS_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        with:
          command: ${{ github.event.inputs.action || 'up' }}
          project: hackathon26
          stack: ${{ github.event.inputs.stack || 'production' }}
          compose-files: compose.yaml
          config-vars-init-random: POSTGRES_PASSWORD
          config-env-vars: |
            SESSION_SECRET
            CONSENTKEYS_CLIENT_SECRET
            SMTP_PASSWORD

      - name: Deployment Summary
        uses: DefangLabs/defang-github-action@v2
        with:
          command: services
          project: hackathon26
          stack: ${{ github.event.inputs.stack || 'production' }}
          compose-files: compose.yaml
    environment: defang-production
